export const GET_USER_PROFILES = 'GET_USER_PROFILES';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_REPOS = 'GET_USER_REPOS';
export const FAILED_TO_GET_USER_REPOS = 'FAILED_TO_GET_USER_REPOS';
export const FAILED_TO_GET_USER_PROFILES = 'FAILED_TO_GET_USER_PROFILES';
export const FAILED_TO_GET_USER_PROFILE = 'FAILED_TO_GET_USER_PROFILE';